import argparse
import os
import matplotlib.pyplot as plt
from parse_data import parse_cameras_data, parse_json
import cv2
import numpy as np

parser = argparse.ArgumentParser()
parser.add_argument(
    '-keypoints1', 
    type=str,
    help='keypoints1 json file', 
    required=True)
parser.add_argument(
    '-keypoints2', 
    type=str, 
    help='keypoints2 json file', 
    required=True)
parser.add_argument(
    '-cameras_data', 
    type=str, 
    help='folder with calibration data (generated by start_calibrate.py)', 
    required=True)

args = parser.parse_args()

projMatrix1, projMatrix2 = parse_cameras_data(args.cameras_data)[-2:]

keypoints1, keypointsFull1 = parse_json(args.keypoints1)
keypoints2, keypointsFull2 = parse_json(args.keypoints2)


points3D = cv2.triangulatePoints(
    projMatrix1, 
    projMatrix2,
    keypoints1,
    keypoints2
)


points3D = np.array(points3D)[:,:-1]

print(points3D)
